"""JalRakshak Garden AI — Comprehensive Plant Knowledge Engine.

Detailed botanical, moisture, temperature, and cultural knowledge for Indian
and Gujarat terrace / kitchen garden crops.
"""
from __future__ import annotations

from typing import Any, Optional


PLANT_KNOWLEDGE_BASE: dict[str, dict[str, Any]] = {
    "tomato": {
        "canonical_name": "Tomato",
        "name_gu": "ટામેટું",
        "name_hi": "टमाटर",
        "scientific_name": "Solanum lycopersicum",
        "soil_moisture_target_min": 40.0,
        "soil_moisture_target_max": 70.0,
        "critical_low_moisture": 25.0,
        "temp_min_c": 18.0,
        "temp_max_c": 35.0,
        "heat_sensitive": True,
        "watering_frequency": "Every 1-2 days depending on heat",
        "growth_stages": ["Seedling", "Vegetative", "Flowering", "Fruiting", "Ripening"],
        "soil_preference": "Well-drained sandy loam rich in organic compost",
        "sunlight": "Full sun (6-8 hours daily)",
        "drought_tolerance": "moderate",
        "water_depth": "Deep root watering",
        "care_notes": "Consistent moisture prevents blossom end rot and fruit splitting. Avoid wetting foliage to prevent fungal blight.",
    },
    "chilli": {
        "canonical_name": "Chilli",
        "name_gu": "મરચું",
        "name_hi": "मिर्च",
        "scientific_name": "Capsicum annuum",
        "soil_moisture_target_min": 35.0,
        "soil_moisture_target_max": 65.0,
        "critical_low_moisture": 20.0,
        "temp_min_c": 20.0,
        "temp_max_c": 38.0,
        "heat_sensitive": False,
        "watering_frequency": "Every 2-3 days",
        "growth_stages": ["Seedling", "Vegetative", "Budding", "Fruiting", "Harvest"],
        "soil_preference": "Light loamy soil with excellent drainage",
        "sunlight": "Full sun (6+ hours)",
        "drought_tolerance": "high",
        "water_depth": "Moderate base watering",
        "care_notes": "Extremely susceptible to root rot if waterlogged. Let the top 2-3 cm dry slightly before rewatering.",
    },
    "okra": {
        "canonical_name": "Okra (Bhindi)",
        "name_gu": "ભીંડા",
        "name_hi": "भिन्डी",
        "scientific_name": "Abelmoschus esculentus",
        "soil_moisture_target_min": 40.0,
        "soil_moisture_target_max": 70.0,
        "critical_low_moisture": 25.0,
        "temp_min_c": 22.0,
        "temp_max_c": 42.0,
        "heat_sensitive": False,
        "watering_frequency": "Every 2 days during heat, 3-4 days in mild weather",
        "growth_stages": ["Germination", "Vegetative", "Flowering", "Pod development"],
        "soil_preference": "Fertile, loose loamy soil with neutral pH",
        "sunlight": "Full direct sunlight",
        "drought_tolerance": "high",
        "water_depth": "Deep soaking",
        "care_notes": "Loves hot Gujarat summer weather. Needs consistent watering during flowering and pod enlargement.",
    },
    "coriander": {
        "canonical_name": "Coriander (Dhaniya)",
        "name_gu": "ધાણા / કોથમીર",
        "name_hi": "धनिया",
        "scientific_name": "Coriandrum sativum",
        "soil_moisture_target_min": 45.0,
        "soil_moisture_target_max": 75.0,
        "critical_low_moisture": 30.0,
        "temp_min_c": 12.0,
        "temp_max_c": 28.0,
        "heat_sensitive": True,
        "watering_frequency": "Daily shallow misting/watering in warmth",
        "growth_stages": ["Emergence", "Leafy rosette", "Stem elongation", "Bolting"],
        "soil_preference": "Friable, fertile loamy soil that retains slight moisture",
        "sunlight": "Partial shade / morning sun during hot months",
        "drought_tolerance": "low",
        "water_depth": "Shallow, gentle watering",
        "care_notes": "Bolts quickly into flower when temperatures exceed 30°C or moisture fluctuates. Provide afternoon shade.",
    },
    "tulsi": {
        "canonical_name": "Holy Basil (Tulsi)",
        "name_gu": "તુલસી",
        "name_hi": "तुलसी",
        "scientific_name": "Ocimum tenuiflorum",
        "soil_moisture_target_min": 30.0,
        "soil_moisture_target_max": 60.0,
        "critical_low_moisture": 18.0,
        "temp_min_c": 15.0,
        "temp_max_c": 40.0,
        "heat_sensitive": False,
        "watering_frequency": "Every 2-4 days",
        "growth_stages": ["Seedling", "Bushy vegetative", "Flowering spike (Manjari)"],
        "soil_preference": "Porous, aerated potting mix or well-draining garden soil",
        "sunlight": "4-6 hours direct sun",
        "drought_tolerance": "high",
        "water_depth": "Base watering when topsoil is dry",
        "care_notes": "Overwatering causes leaf drop and yellowing. Pinch off flower spikes (manjari) to promote dense aromatic foliage.",
    },
    "mint": {
        "canonical_name": "Mint (Pudina)",
        "name_gu": "ફુદીનો",
        "name_hi": "पुदीना",
        "scientific_name": "Mentha spicata",
        "soil_moisture_target_min": 50.0,
        "soil_moisture_target_max": 80.0,
        "critical_low_moisture": 35.0,
        "temp_min_c": 15.0,
        "temp_max_c": 35.0,
        "heat_sensitive": True,
        "watering_frequency": "Daily or every alternate day",
        "growth_stages": ["Runner spreading", "Foliage growth", "Flowering"],
        "soil_preference": "Moist, rich humus soil with high organic matter",
        "sunlight": "Morning sun or partial shade",
        "drought_tolerance": "low",
        "water_depth": "Frequent, even moisture",
        "care_notes": "Requires high moisture. Best planted in containers to prevent invasive underground rhizomes.",
    },
    "neem": {
        "canonical_name": "Neem",
        "name_gu": "લીમડો",
        "name_hi": "नीम",
        "scientific_name": "Azadirachta indica",
        "soil_moisture_target_min": 20.0,
        "soil_moisture_target_max": 50.0,
        "critical_low_moisture": 12.0,
        "temp_min_c": 10.0,
        "temp_max_c": 48.0,
        "heat_sensitive": False,
        "watering_frequency": "Once a week for saplings; mature trees rely on rainfall",
        "growth_stages": ["Sapling", "Juvenile tree", "Mature tree"],
        "soil_preference": "Tolerates poor, sandy, alkaline, or stony soil",
        "sunlight": "Intense direct sunlight",
        "drought_tolerance": "very high",
        "water_depth": "Deep soak once established",
        "care_notes": "Exceptional drought and heat resistance. Young potted saplings need moderate watering until root system matures.",
    },
    "marigold": {
        "canonical_name": "Marigold (Genda)",
        "name_gu": "ગલગોટા",
        "name_hi": "गेंदा",
        "scientific_name": "Tagetes erecta",
        "soil_moisture_target_min": 35.0,
        "soil_moisture_target_max": 65.0,
        "critical_low_moisture": 22.0,
        "temp_min_c": 15.0,
        "temp_max_c": 38.0,
        "heat_sensitive": False,
        "watering_frequency": "Every 2-3 days",
        "growth_stages": ["Seedling", "Branching", "Budding", "Full bloom"],
        "soil_preference": "Well-drained garden soil",
        "sunlight": "Full sun",
        "drought_tolerance": "moderate",
        "water_depth": "Base watering",
        "care_notes": "Natural companion plant that deters nematodes and pests. Deadhead spent flowers for continuous blooming.",
    },
    "rose": {
        "canonical_name": "Rose (Gulab)",
        "name_gu": "ગુલાબ",
        "name_hi": "गुलाब",
        "scientific_name": "Rosa indica",
        "soil_moisture_target_min": 40.0,
        "soil_moisture_target_max": 70.0,
        "critical_low_moisture": 25.0,
        "temp_min_c": 15.0,
        "temp_max_c": 36.0,
        "heat_sensitive": True,
        "watering_frequency": "Every 2 days; water deeply early morning",
        "growth_stages": ["New cane growth", "Budding", "Flushing", "Dormancy"],
        "soil_preference": "Rich, well-aerated loam with compost and good drainage",
        "sunlight": "At least 5-6 hours of direct sun",
        "drought_tolerance": "moderate",
        "water_depth": "Deep root soaking; keep mulch layer 5 cm thick",
        "care_notes": "Avoid wetting foliage late in the day to ward off black spot and powdery mildew. Mulching saves up to 40% water in summer.",
    },
    "lemon": {
        "canonical_name": "Lemon / Lime (Nimboo)",
        "name_gu": "લીંબુ",
        "name_hi": "नींबू",
        "scientific_name": "Citrus limon",
        "soil_moisture_target_min": 35.0,
        "soil_moisture_target_max": 65.0,
        "critical_low_moisture": 20.0,
        "temp_min_c": 15.0,
        "temp_max_c": 42.0,
        "heat_sensitive": False,
        "watering_frequency": "Deep watering every 3-5 days",
        "growth_stages": ["Flush", "Blossom", "Fruit set", "Fruit expansion", "Maturity"],
        "soil_preference": "Slightly acidic to neutral sandy loam, non-saline",
        "sunlight": "Full sun (minimum 6 hours)",
        "drought_tolerance": "high",
        "water_depth": "Deep slow irrigation around root drip line",
        "care_notes": "Deep, infrequent irrigation encourages deep taproots. Yellow leaves often indicate overwatering or iron chlorosis.",
    },
    "curry leaf": {
        "canonical_name": "Curry Leaf (Kadi Patta)",
        "name_gu": "મીઠો લીમડો / કઢી લીમડો",
        "name_hi": "कढ़ी पत्ता",
        "scientific_name": "Murraya koenigii",
        "soil_moisture_target_min": 35.0,
        "soil_moisture_target_max": 65.0,
        "critical_low_moisture": 22.0,
        "temp_min_c": 18.0,
        "temp_max_c": 40.0,
        "heat_sensitive": False,
        "watering_frequency": "Every 2-3 days in summer, weekly in winter",
        "growth_stages": ["Sapling", "Active flushing", "Foliage maturity"],
        "soil_preference": "Well-draining red or loamy soil enriched with cow manure",
        "sunlight": "Bright sunlight to light afternoon shade",
        "drought_tolerance": "moderate",
        "water_depth": "Medium soak",
        "care_notes": "Loves buttermilk or sour curd drench monthly. Ensure drainage holes in pots never clog.",
    },
    "brinjal": {
        "canonical_name": "Brinjal / Eggplant (Baingan / Reengna)",
        "name_gu": "રીંગણા",
        "name_hi": "बैंगन",
        "scientific_name": "Solanum melongena",
        "soil_moisture_target_min": 40.0,
        "soil_moisture_target_max": 70.0,
        "critical_low_moisture": 25.0,
        "temp_min_c": 20.0,
        "temp_max_c": 40.0,
        "heat_sensitive": False,
        "watering_frequency": "Every 2 days during fruiting",
        "growth_stages": ["Seedling", "Branching", "Purple flowering", "Fruit harvest"],
        "soil_preference": "Deep, rich loam with compost",
        "sunlight": "Full sun",
        "drought_tolerance": "moderate",
        "water_depth": "Deep soaking at base",
        "care_notes": "Heavy feeder and heavy drinker during fruit sizing. Regular mulching maintains cool root temperature.",
    },
    "cucumber": {
        "canonical_name": "Cucumber (Kakdi / Kheera)",
        "name_gu": "કાકડી",
        "name_hi": "खीरा / ककड़ी",
        "scientific_name": "Cucumis sativus",
        "soil_moisture_target_min": 45.0,
        "soil_moisture_target_max": 75.0,
        "critical_low_moisture": 30.0,
        "temp_min_c": 18.0,
        "temp_max_c": 38.0,
        "heat_sensitive": True,
        "watering_frequency": "Daily or alternate mornings",
        "growth_stages": ["Vining", "Tendril climbing", "Yellow flowering", "Fruit elongation"],
        "soil_preference": "Loose, organic-rich soil that holds moisture without bogging",
        "sunlight": "Full morning sun with partial afternoon protection in peak summer",
        "drought_tolerance": "low",
        "water_depth": "Consistent root-zone hydration",
        "care_notes": "Irregular watering leads to bitter cucumbers. Drip irrigation or morning watering at ground level is ideal.",
    },
    "bottle gourd": {
        "canonical_name": "Bottle Gourd (Doodhi / Lauki)",
        "name_gu": "દૂધી",
        "name_hi": "लौकी",
        "scientific_name": "Lagenaria siceraria",
        "soil_moisture_target_min": 40.0,
        "soil_moisture_target_max": 70.0,
        "critical_low_moisture": 25.0,
        "temp_min_c": 22.0,
        "temp_max_c": 42.0,
        "heat_sensitive": False,
        "watering_frequency": "Every 2 days; high volume on trellis vines",
        "growth_stages": ["Seedling", "Vigorous vine", "White flowers (night)", "Gourd expansion"],
        "soil_preference": "Fertile, sandy loam with compost",
        "sunlight": "Full sun",
        "drought_tolerance": "moderate",
        "water_depth": "Deep root-basin soaking",
        "care_notes": "Extensive root system needs ample water when supporting heavy gourds. Hand-pollinate evening white flowers if fruit drops prematurely.",
    },
    "spinach": {
        "canonical_name": "Spinach / Palak",
        "name_gu": "પાલક",
        "name_hi": "पालक",
        "scientific_name": "Spinacia oleracea",
        "soil_moisture_target_min": 50.0,
        "soil_moisture_target_max": 75.0,
        "critical_low_moisture": 35.0,
        "temp_min_c": 10.0,
        "temp_max_c": 30.0,
        "heat_sensitive": True,
        "watering_frequency": "Daily shallow watering",
        "growth_stages": ["Cotyledon", "Tender leaves", "Broad leaf harvest", "Bolting"],
        "soil_preference": "Nitrogen-rich, loose, consistently moist soil",
        "sunlight": "Partial shade during warm days",
        "drought_tolerance": "low",
        "water_depth": "Gentle, evenly distributed moisture",
        "care_notes": "Fast growing greens. Moisture stress makes leaves tough and induces premature flowering.",
    },
    "aloe vera": {
        "canonical_name": "Aloe Vera (Kunwarpathu)",
        "name_gu": "કુંવારપાઠું",
        "name_hi": "एलोवेरा / घृतकुमारी",
        "scientific_name": "Aloe barbadensis miller",
        "soil_moisture_target_min": 15.0,
        "soil_moisture_target_max": 45.0,
        "critical_low_moisture": 10.0,
        "temp_min_c": 12.0,
        "temp_max_c": 45.0,
        "heat_sensitive": False,
        "watering_frequency": "Every 7-14 days",
        "growth_stages": ["Offset pup", "Rosette expansion", "Mature gel leaves"],
        "soil_preference": "Gritty, sandy succulent cactus mix with rapid drainage",
        "sunlight": "Bright indirect sunlight or partial sun",
        "drought_tolerance": "very high",
        "water_depth": "Soak and allow complete dry-out",
        "care_notes": "Number one killer is overwatering. Fleshy leaves store substantial water reserves. Never let water sit in leaf crown.",
    },
}


def lookup_plant_knowledge(name_query: str) -> dict[str, Any]:
    """Look up plant by common name, scientific name, Hindi, or Gujarati."""
    if not name_query:
        return PLANT_KNOWLEDGE_BASE["tomato"]  # safe default

    q = name_query.strip().lower()
    for key, data in PLANT_KNOWLEDGE_BASE.items():
        if key in q or q in key:
            return data
        if q in data["canonical_name"].lower():
            return data
        if q in data["name_gu"].lower() or data["name_gu"].lower() in q:
            return data
        if q in data["name_hi"].lower() or data["name_hi"].lower() in q:
            return data

    # Default fallback with sensible conservative metrics
    return {
        "canonical_name": name_query.capitalize(),
        "name_gu": name_query,
        "name_hi": name_query,
        "scientific_name": "Plantae",
        "soil_moisture_target_min": 40.0,
        "soil_moisture_target_max": 65.0,
        "critical_low_moisture": 25.0,
        "temp_min_c": 18.0,
        "temp_max_c": 36.0,
        "heat_sensitive": True,
        "watering_frequency": "Every 2 days",
        "growth_stages": ["Seedling", "Vegetative", "Flowering", "Maturity"],
        "soil_preference": "Loamy garden soil",
        "sunlight": "Partial to full sun",
        "drought_tolerance": "moderate",
        "water_depth": "Moderate base watering",
        "care_notes": "Inspect topsoil 2-3 cm before watering.",
    }


def list_all_supported_plants() -> list[dict[str, Any]]:
    """Return all plants in the knowledge base."""
    return [
        {
            "id": key,
            **data,
        }
        for key, data in PLANT_KNOWLEDGE_BASE.items()
    ]
