import React, { useEffect, useMemo, useState } from 'react'
import { createRoot } from 'react-dom/client'
import {
  Sprout, Droplets, Sun, Leaf, ShieldCheck, WifiOff, CheckCircle2, Circle,
  Camera, BookOpen, Plus, ArrowUpRight, CloudSun, Waves, CircleHelp, RefreshCw,
  Sparkles, X, Menu, ThermometerSun, MapPin, Clock3, Info, ChevronDown
} from 'lucide-react'
import './styles.css'

const API = 'http://127.0.0.1:8000'
const defaults = { plant: 'Tomato', location: 'Gujarat, India', soil: 'loamy', moisture: 'slightly dry', weather: 'hot and sunny', garden_size: 'small', water_source: 'tap / stored water', use_ai: true }
const offlinePlan = (g) => {
  const wet = g.moisture.toLowerCase().includes('wet')
  const dry = g.moisture.toLowerCase().includes('dry')
  const hot = /hot|sunny|heat/i.test(g.weather)
  return {
    title: `Water-smart plan for ${g.plant}`,
    summary: wet ? 'Pause watering and check that excess water can drain away.' : dry ? 'Water slowly at the base until the root zone is evenly moist, then let excess drain.' : hot ? 'Check soil near the roots. If the top 2–3 cm is dry, water at the base in the early morning.' : 'Check the top 2–3 cm of soil before watering. Water only if it feels dry.',
    timing: wet ? 'Recheck the top 2–3 cm later today.' : hot ? 'Early morning is usually best. Inspect soil daily during a heatwave.' : 'Recheck tomorrow, or sooner if weather turns hot or windy.',
    amount: 'Use slow, deep watering rather than frequent shallow splashes. Adjust for plant size, pot, and drainage.',
    checklist: ['Mulch with 3–5 cm of clean organic material where appropriate; keep it away from stems.', 'Water the soil rather than leaves to reduce evaporation.', 'Check pots more often than in-ground beds.'],
    watch_for: 'Wilting can mean dry soil or waterlogged roots. Check the soil before watering.',
    source: 'offline rules', confidence: 'General guidance; verify conditions in your garden.'
  }
}
function App() {
  const [garden, setGarden] = useState(defaults)
  const [plan, setPlan] = useState(offlinePlan(defaults))
  const [aiStatus, setAiStatus] = useState({ checked: false, ollama_available: false, model: 'gemma3:4b' })
  const [busy, setBusy] = useState(false)
  const [toast, setToast] = useState('')
  const [journal, setJournal] = useState([])
  const [note, setNote] = useState('')
  const [photo, setPhoto] = useState(null)
  const [photoPreview, setPhotoPreview] = useState('')
  const [photoResult, setPhotoResult] = useState('')
  const [photoBusy, setPhotoBusy] = useState(false)
  const [tab, setTab] = useState('plan')
  const [menuOpen, setMenuOpen] = useState(false)
  const [apiAvailable, setApiAvailable] = useState(false)
  const [tasksDone, setTasksDone] = useState([false, false, false])
  const doneCount = tasksDone.filter(Boolean).length

  const update = (key, value) => setGarden(prev => ({ ...prev, [key]: value }))
  const showToast = (msg) => { setToast(msg); window.setTimeout(() => setToast(''), 3000) }

  async function checkHealth() {
    try {
      const res = await fetch(`${API}/api/health`, { signal: AbortSignal.timeout(2500) })
      const data = await res.json()
      setAiStatus({ checked: true, ...data })
      setApiAvailable(true)
    } catch {
      setApiAvailable(false)
      setAiStatus({ checked: true, ollama_available: false, model: 'gemma3:4b' })
    }
  }
  async function loadJournal() {
    try {
      const res = await fetch(`${API}/api/journal`, { signal: AbortSignal.timeout(2500) })
      if (res.ok) setJournal(await res.json())
    } catch {}
  }
  useEffect(() => {
    checkHealth(); loadJournal()
    if ('serviceWorker' in navigator) navigator.serviceWorker.register('/sw.js').catch(() => {})
  }, [])

  async function generatePlan() {
    setBusy(true)
    const local = offlinePlan(garden)
    setPlan(local)
    try {
      const res = await fetch(`${API}/api/recommend`, {
        method: 'POST', headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(garden), signal: AbortSignal.timeout(95000)
      })
      if (res.ok) {
        const data = await res.json()
        setPlan(data)
        showToast(data.source?.includes('local AI') ? 'Plan generated by your local AI.' : 'Offline garden guidance ready.')
      } else showToast('Using offline garden guidance.')
    } catch {
      showToast('Backend unavailable. Using offline garden guidance.')
    } finally { setBusy(false) }
  }

  function handlePhoto(e) {
    const file = e.target.files?.[0]
    if (!file) return
    if (file.size > 7 * 1024 * 1024) { showToast('Choose an image under 7 MB.'); return }
    setPhoto(file)
    const reader = new FileReader()
    reader.onload = () => setPhotoPreview(String(reader.result))
    reader.readAsDataURL(file)
    setPhotoResult('')
  }
  async function analyzePhoto() {
    if (!photoPreview) return
    setPhotoBusy(true)
    try {
      const res = await fetch(`${API}/api/analyze-photo`, {
        method: 'POST', headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ image_data_url: photoPreview, plant_context: garden.plant, location: garden.location }),
        signal: AbortSignal.timeout(95000)
      })
      const data = await res.json()
      if (!res.ok) throw new Error(data.detail || 'Local vision model unavailable.')
      setPhotoResult(data.analysis)
      showToast('Photo analyzed on your local AI setup.')
    } catch (err) {
      setPhotoResult(`Local photo analysis is not available right now.\n\n${err.message}\n\nYou can still save this observation to your garden journal.`)
    } finally { setPhotoBusy(false) }
  }

  async function saveJournal() {
    if (!note.trim()) { showToast('Add a short observation first.'); return }
    const entry = { plant: garden.plant, note: note.trim(), moisture: garden.moisture, recommendation: plan.summary || '' }
    try {
      const res = await fetch(`${API}/api/journal`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(entry) })
      if (!res.ok) throw new Error('API error')
      const saved = await res.json()
      setJournal(prev => [saved, ...prev])
      setNote('')
      showToast('Saved privately to your local journal.')
    } catch {
      const saved = { ...entry, id: `local-${Date.now()}`, created_at: new Date().toISOString() }
      setJournal(prev => [saved, ...prev])
      setNote('')
      showToast('Saved for this session. Start the backend for persistent local storage.')
    }
  }

  const currentMode = plan.source?.includes('local AI') ? 'Local AI' : 'Offline guide'
  const dateLabel = useMemo(() => new Intl.DateTimeFormat('en-IN', { weekday: 'short', day: 'numeric', month: 'short' }).format(new Date()), [])

  return <div className="app-shell">
    <aside className={`sidebar ${menuOpen ? 'open' : ''}`}>
      <div className="brand"><div className="brand-mark"><Sprout size={23}/></div><div><strong>JalRakshak</strong><span>GARDEN AI</span></div><button className="mobile-close icon-btn" onClick={() => setMenuOpen(false)}><X size={18}/></button></div>
      <div className="workspace-label">YOUR GARDEN</div>
      <button className={`nav-item ${tab === 'plan' ? 'active' : ''}`} onClick={() => {setTab('plan');setMenuOpen(false)}}><Droplets size={18}/> Water plan</button>
      <button className={`nav-item ${tab === 'observe' ? 'active' : ''}`} onClick={() => {setTab('observe');setMenuOpen(false)}}><Camera size={18}/> Plant observer <span className="nav-dot"/></button>
      <button className={`nav-item ${tab === 'journal' ? 'active' : ''}`} onClick={() => {setTab('journal');setMenuOpen(false)}}><BookOpen size={18}/> Garden journal <span className="nav-count">{journal.length}</span></button>
      <div className="sidebar-spacer"/>
      <div className="privacy-card"><div className="privacy-icon"><ShieldCheck size={18}/></div><strong>Your garden, your data.</strong><p>Designed to work locally. No cloud AI account required.</p><div className="privacy-status"><span className={apiAvailable ? 'status-dot green' : 'status-dot'}/>{apiAvailable ? 'Local backend connected' : 'Offline mode available'}</div></div>
      <div className="sidebar-foot"><span className="avatar">JG</span><div><strong>My garden</strong><span>Private workspace</span></div><ChevronDown size={15} className="muted-icon"/></div>
    </aside>

    <main className="main-area">
      <header className="topbar"><button className="mobile-menu icon-btn" onClick={() => setMenuOpen(true)}><Menu size={21}/></button><div className="breadcrumb">Workspace <span>/</span> <strong>{tab === 'plan' ? 'Water plan' : tab === 'observe' ? 'Plant observer' : 'Garden journal'}</strong></div><div className="top-actions"><div className="date-chip"><Clock3 size={15}/>{dateLabel}</div><div className={`connection-pill ${aiStatus.ollama_available ? 'connected' : ''}`}><span className="status-dot"/> {aiStatus.ollama_available ? 'Local AI ready' : 'Local-first mode'}</div><button className="icon-btn refresh-btn" aria-label="Refresh status" onClick={checkHealth}><RefreshCw size={16}/></button></div></header>

      <div className="content">
        <section className="welcome-row"><div><div className="eyebrow"><span className="eyebrow-line"/> WATER-WISE LIVING</div><h1>Grow well. <em>Waste less.</em></h1><p className="welcome-copy">Small, thoughtful actions make a healthier garden. Let's check what yours needs today.</p></div><div className="welcome-illustration"><div className="sun-disc"><Sun size={29}/></div><div className="hill hill-back"/><div className="hill hill-front"/><div className="plant-art"><Sprout size={58}/></div></div></section>

        <section className="metrics-grid">
          <div className="metric-card"><div className="metric-top"><span className="metric-icon water"><Droplets size={18}/></span><span className="metric-label">TODAY'S FOCUS</span></div><div className="metric-value">Water wisely</div><div className="metric-note"><span className="mini-leaf"><Leaf size={12}/></span> Check soil before watering</div></div>
          <div className="metric-card"><div className="metric-top"><span className="metric-icon sun"><Sun size={18}/></span><span className="metric-label">CONDITIONS</span></div><div className="metric-value">{garden.weather === 'hot and sunny' ? 'Warm & bright' : garden.weather === 'rainy / humid' ? 'Rain / humid' : 'Mild conditions'}</div><div className="metric-note"><ThermometerSun size={13}/> Based on your input</div></div>
          <div className="metric-card"><div className="metric-top"><span className="metric-icon leaf"><Leaf size={18}/></span><span className="metric-label">GARDEN JOURNAL</span></div><div className="metric-value">{journal.length} <small>observations</small></div><div className="metric-note"><BookOpen size={13}/> Stored locally when backend runs</div></div>
        </section>

        {tab === 'plan' && <div className="dashboard-grid">
          <section className="panel garden-panel">
            <div className="panel-heading"><div><div className="section-kicker">PERSONALIZE YOUR PLAN</div><h2>What's happening in your garden?</h2><p>Tell us a little about your plant and its surroundings.</p></div><div className="panel-symbol"><Sprout size={22}/></div></div>
            <div className="form-grid">
              <label className="field"><span>Plant or crop</span><select value={garden.plant} onChange={e => update('plant', e.target.value)}>{['Tomato','Chilli / pepper','Coriander','Tulsi / holy basil','Mint','Rose','Aloe vera','Curry leaf','Lemon','Other plant'].map(v => <option key={v}>{v}</option>)}</select></label>
              <label className="field"><span>Soil type</span><select value={garden.soil} onChange={e => update('soil', e.target.value)}><option value="sandy">Sandy · drains quickly</option><option value="loamy">Loamy · balanced</option><option value="clay">Clay · holds moisture</option><option value="potting mix">Potting mix</option></select></label>
              <label className="field"><span>Soil moisture</span><select value={garden.moisture} onChange={e => update('moisture', e.target.value)}><option value="very dry">Very dry</option><option value="dry">Dry</option><option value="slightly dry">Slightly dry</option><option value="moist">Moist</option><option value="wet">Wet / soggy</option></select></label>
              <label className="field"><span>Today's weather</span><select value={garden.weather} onChange={e => update('weather', e.target.value)}><option value="hot and sunny">Hot and sunny</option><option value="warm and breezy">Warm and breezy</option><option value="mild / cloudy">Mild / cloudy</option><option value="rainy / humid">Rainy / humid</option></select></label>
              <label className="field"><span>Garden size</span><select value={garden.garden_size} onChange={e => update('garden_size', e.target.value)}><option value="balcony pots">Balcony pots</option><option value="small">Small garden</option><option value="medium">Medium garden</option><option value="large">Large garden</option></select></label>
              <label className="field"><span>Water source</span><select value={garden.water_source} onChange={e => update('water_source', e.target.value)}><option value="tap / stored water">Tap / stored water</option><option value="rainwater">Collected rainwater</option><option value="drip irrigation">Drip irrigation</option><option value="well water">Well water</option></select></label>
            </div>
            <div className="ai-toggle-row"><div className="toggle-copy"><span className="toggle-icon"><Sparkles size={17}/></span><div><strong>Use my local AI model</strong><p>Private inference via Ollama. Falls back to offline rules.</p></div></div><button role="switch" aria-checked={garden.use_ai} className={`toggle ${garden.use_ai ? 'on' : ''}`} onClick={() => update('use_ai', !garden.use_ai)}><span/></button></div>
            <button className="primary-btn full-btn" onClick={generatePlan} disabled={busy}>{busy ? <><RefreshCw size={17} className="spin"/> Thinking locally…</> : <><Sparkles size={17}/> Generate my garden plan <ArrowUpRight size={16}/></>}</button>
          </section>

          <section className="panel plan-panel">
            <div className="plan-header"><div><div className="section-kicker">YOUR DAILY GUIDE</div><h2>{plan.title}</h2></div><span className={`source-chip ${currentMode === 'Local AI' ? 'ai-chip' : ''}`}><span className="status-dot"/>{currentMode}</span></div>
            <div className="recommendation-highlight"><div className="highlight-icon"><Droplets size={20}/></div><div><span className="highlight-label">RECOMMENDED ACTION</span><p>{plan.summary}</p></div></div>
            <div className="plan-detail"><div className="detail-icon"><Clock3 size={17}/></div><div><strong>When to do it</strong><p>{plan.timing}</p></div></div>
            <div className="plan-detail"><div className="detail-icon"><Waves size={17}/></div><div><strong>How much water?</strong><p>{plan.amount}</p></div></div>
            <div className="checklist-block"><div className="checklist-title"><strong>Small steps, big impact</strong><span>{plan.checklist?.length || 0} tips</span></div>{(plan.checklist || []).slice(0,4).map((item,i) => <div className="tip-row" key={i}><span className="tip-check"><CheckCircle2 size={16}/></span><p>{item}</p></div>)}</div>
            <div className="caution-note"><Info size={16}/><p>{plan.watch_for || 'Check actual soil moisture before watering. Advice is general and may not fit every plant.'}</p></div>
            {plan.ai_note && <div className="inline-notice"><WifiOff size={15}/>{plan.ai_note}</div>}
            <div className="plan-footer"><span><ShieldCheck size={14}/> Your inputs stay on this device</span><span className="confidence">{plan.confidence}</span></div>
          </section>
        </div>}

        {tab === 'observe' && <section className="panel observer-panel">
          <div className="panel-heading"><div><div className="section-kicker">FIELD OBSERVATION</div><h2>Take a closer look</h2><p>Photograph a plant or leaf and ask your local model for cautious observations.</p></div><div className="panel-symbol"><Camera size={22}/></div></div>
          <div className="observer-grid">
            <div className="upload-zone">{photoPreview ? <div className="photo-preview-wrap"><img src={photoPreview} alt="Selected plant preview"/><button className="remove-photo" onClick={() => {setPhoto(null);setPhotoPreview('');setPhotoResult('')}}><X size={16}/></button></div> : <label className="upload-label"><div className="upload-icon"><Camera size={25}/></div><strong>Drop a photo into your workflow</strong><span>Choose a leaf, flower, or whole plant image</span><small>JPG, PNG or WEBP · max 7 MB</small><input type="file" accept="image/*" capture="environment" onChange={handlePhoto}/><span className="choose-file">Choose photo</span></label>}</div>
            <div className="observer-info"><div className="privacy-callout"><ShieldCheck size={18}/><div><strong>Local by design</strong><p>The photo is sent to your own Ollama service, not a hosted AI API.</p></div></div><div className="observer-note"><CircleHelp size={17}/><p>AI can miss look-alike species or plant diseases. Use this as a learning aid, not a definitive diagnosis.</p></div><button className="primary-btn full-btn" disabled={!photoPreview || photoBusy} onClick={analyzePhoto}>{photoBusy ? <><RefreshCw className="spin" size={17}/> Analyzing locally…</> : <><Sparkles size={17}/> Analyze with local AI</>}</button></div>
          </div>
          {photoResult && <div className="photo-result"><div className="result-title"><Sparkles size={17}/> Local AI observations <span className="source-chip ai-chip">On-device network</span></div><pre>{photoResult}</pre></div>}
          <div className="journal-compose"><div><strong>Record what you noticed</strong><p>Save a note even if AI is unavailable.</p></div><textarea value={note} onChange={e => setNote(e.target.value)} placeholder="E.g. New leaves look healthy; soil was dry about 2 cm down…" rows={3}/><button className="primary-btn" onClick={saveJournal}><Plus size={17}/> Save observation</button></div>
        </section>}

        {tab === 'journal' && <section className="panel journal-panel"><div className="panel-heading"><div><div className="section-kicker">YOUR FIELD NOTES</div><h2>A little progress, every day</h2><p>Your garden observations, kept close to home.</p></div><div className="panel-symbol"><BookOpen size={22}/></div></div><div className="journal-compose journal-top-compose"><strong>Add a quick note</strong><textarea value={note} onChange={e => setNote(e.target.value)} placeholder="What did you notice in your garden today?" rows={3}/><button className="primary-btn" onClick={saveJournal}><Plus size={17}/> Save to journal</button></div><div className="journal-list">{journal.length ? journal.map((entry,i) => <article className="journal-entry" key={entry.id ?? i}><div className="entry-icon"><Leaf size={18}/></div><div className="entry-body"><div className="entry-top"><strong>{entry.plant}</strong><span>{entry.created_at ? new Date(entry.created_at).toLocaleString() : 'Just now'}</span></div><p>{entry.note}</p>{entry.recommendation && <small>Plan: {entry.recommendation}</small>}</div></article>) : <div className="empty-state"><div className="empty-icon"><BookOpen size={25}/></div><strong>Your journal starts here</strong><p>Save your first plant observation to build a private record of your garden.</p><button className="secondary-btn" onClick={() => setTab('observe')}>Add an observation <ArrowUpRight size={15}/></button></div>}</div></section>}

        <section className="outdoor-strip"><div className="outdoor-icon"><Sprout size={21}/></div><div className="outdoor-copy"><span>YOUR SCREEN-FREE CHALLENGE</span><strong>Spend 5 minutes with your plants today.</strong><p>Touch the soil, notice a new leaf, or listen for birds. Then put your phone away.</p></div><div className="challenge-progress"><div className="progress-label"><span>{doneCount} of 3 complete</span><strong>{Math.round(doneCount/3*100)}%</strong></div><div className="progress-track"><span style={{width:`${doneCount/3*100}%`}}/></div></div></section>
        <section className="mission-list">{['Check soil moisture with your finger','Look for one new leaf or flower','Water only if the plant needs it'].map((task,i) => <button key={task} className={`mission ${tasksDone[i] ? 'completed' : ''}`} onClick={() => setTasksDone(prev => prev.map((v,j) => j === i ? !v : v))}>{tasksDone[i] ? <CheckCircle2 size={17}/> : <Circle size={17}/>}<span>{task}</span></button>)}</section>
        <footer className="footer"><span>JalRakshak Garden AI <span className="footer-dot">•</span> Made for mindful growing</span><span><ShieldCheck size={13}/> Local-first · No cloud AI required</span></footer>
      </div>
    </main>
    {toast && <div className="toast"><CheckCircle2 size={17}/>{toast}</div>}
  </div>
}
createRoot(document.getElementById('root')).render(<App />)
